"use strict";

var fs = require("fs")

var exports = module.exports = {};
  
exports.createFile =  function(fileName){
    checkJsFile(fileName)
    checkFileNotExist(fileName)
    fs.writeFile(fileName, '// Generated by JsIo.js\n');
    console.info('File '+fileName+' created with success !')
  }
  
exports.deleteFile =  function(fileName){
    checkJsFile(fileName)
    checkFileExist(fileName)
    fs.unlinkSync(fileName);
    console.info('File '+fileName+' deleted with success !')
  }  
  
function checkJsFile(fileName){
  if(fileName === undefined)
    throw "file name is missing";
  if(fileName.length < 4 || fileName.substring(fileName.length-3) !== ".js")
    throw fileName+" is not a valid javascript file name";
}  

function checkFileNotExist(fileName){
  if(fs.existsSync(fileName))
    throw fileName+" already exists"
}

function checkFileExist(fileName){
  if(!fs.existsSync(fileName))
    throw fileName+" does not exist"
}
